### ISSUE TITLE
Manifest searching stops recursing below any key named `image`

### ISSUE THREAD

**Issue by coro** [carvel-dev/kbld#109]
**What steps did you take:**
To demonstrate the issue, here is a repro, containing a kbld config, an imgpkg lockfile and a manifest I wish to transform:
```yaml
---
apiVersion: kbld.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.29.0
searchRules:
- keyMatcher:
    path: [spec, image, default]
- keyMatcher:
    path: [spec, nonimage, default]
---
apiVersion: imgpkg.carvel.dev/v1alpha1
images:
- annotations:
    kbld.carvel.dev/id: original-image:1.2.3
  image: updated-image@sha256:2005721c33a949d82bab23099aa3f577932c350bc24d5931932e7440856f6276
kind: ImagesLock
---
spec:
  image:
    default: original-image:1.2.3
  nonimage:
    default: original-image:1.2.3
```

**What happened:**
I ran the kbld command, and only some of the image references were replaced with the resolved image path:
```bash
$ kbld -f manifest.yaml
resolve | final: original-image:1.2.3 -> updated-image@sha256:2005721c33a949d82bab23099aa3f577932c350bc24d5931932e7440856f6276
---
metadata:
  annotations:
    kbld.k14s.io/images: |
      - Metas:
        - Type: preresolved
          URL: updated-image@sha256:2005721c33a949d82bab23099aa3f577932c350bc24d5931932e7440856f6276
        URL: updated-image@sha256:2005721c33a949d82bab23099aa3f577932c350bc24d5931932e7440856f6276
spec:
  image:
    default: original-image:1.2.3 # This is left not updated
  nonimage:
    default: updated-image@sha256:2005721c33a949d82bab23099aa3f577932c350bc24d5931932e7440856f6276 # This is updated
```

This also occurs if you use a valueMatcher for all instances of the image:
```yaml
---
apiVersion: kbld.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.29.0
searchRules:
- valueMatcher:
    image: original-image:1.2.3
---
apiVersion: imgpkg.carvel.dev/v1alpha1
images:
- annotations:
    kbld.carvel.dev/id: original-image:1.2.3
  image: updated-image@sha256:2005721c33a949d82bab23099aa3f577932c350bc24d5931932e7440856f6276
kind: ImagesLock
---
spec:
  image:
    default: original-image:1.2.3
  nonimage:
    default: original-image:1.2.3
```
```bash
$ kbld -f manifest.yaml
resolve | final: original-image:1.2.3 -> updated-image@sha256:2005721c33a949d82bab23099aa3f577932c350bc24d5931932e7440856f6276
---
metadata:
  annotations:
    kbld.k14s.io/images: |
      - Metas:
        - Type: preresolved
          URL: updated-image@sha256:2005721c33a949d82bab23099aa3f577932c350bc24d5931932e7440856f6276
        URL: updated-image@sha256:2005721c33a949d82bab23099aa3f577932c350bc24d5931932e7440856f6276
spec:
  image:
    default: original-image:1.2.3 # This is left not updated
  nonimage:
    default: updated-image@sha256:2005721c33a949d82bab23099aa3f577932c350bc24d5931932e7440856f6276 # This is updated
```

**What did you expect:**
I expected all instances of `original-image:1.2.3` in the manifest to be replaced with `updated-image@sha256:2005721c33a949d82bab23099aa3f577932c350bc24d5931932e7440856f6276`.

**Anything else you would like to add:**
This is important for CRDs that wrap core API components that have an image field in their Spec, e.g. Deployments. If the CRDs are built with kubebuilder, any `//+kubebuilder:default` tags will lead to a CRD that has this kind of manifest, e.g. `<>.spec.image.default`.

**Environment:**

- kbld version (use `kbld --version`): 0.39.0
- Docker registry used (e.g. `Docker HUB`): N/A
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04.5 LTS

If building images using `docker`:
- Docker CLI Version (e.g. `docker version`): N/A

If building images using `buildkit`:
- Buildkit version (e.g. `kubectl buildkit version`): N/A
- Kubernetes version (e.g. `kubectl version`): N/A

If building images using `pack`
- Pack Version (e.g. `pack version`): N/A

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.
