### ISSUE TITLE
Ability to exclude images from ImagesLock

### ISSUE THREAD

**Issue by gabegorelick** [carvel-dev/kbld#155]
**Describe the problem/challenge you have**
I'm using `kbld` to generate an ImagesLock file for use with `imgpkg`, as outlined in https://carvel.dev/imgpkg/docs/latest/air-gapped-workflow/. But not every image should be part of the resulting imgpkg bundle, specifically any images that will be available behind the airgap. For such images, including them 
would at best be wasteful.

Even worse, sometimes images will be available at runtime, and so don't need to be in the imgpkg bundle, but _won't_ be available at build time. For example, you may not have permission to access a registry at build time, but do at runtime.

The current recommended solution is to remove any images you don't want from the ImagesLock file. But this requires that your bundling code know about such images.

**Describe the solution you'd like**
Ability to specify via an annotation that a pod's image(s) should be excluded from an ImagesLock file.

Care would have to be taken to handle omitting a subset of a pod's images in the case where a pod has multiple container images. 

**Anything else you would like to add:**
Slack discussion: https://kubernetes.slack.com/archives/CH8KCCKA5/p1630616269091900

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by pivotaljohn** [comment]
### Triage
This would be a valuable feature for `kbld` as it expands the tool's ability to cover more cases (here: where an image is referenced, but treated differently by the Carvel image handling tools: `kbld` and `imgpkg`). There's a workaround; but there's some downsides (noted, above).

### Next Steps
To move this forward, it would help to hash out a few details:
- how exactly would a particular container's image be excluded from this special treatment?
- how does this feature work for non-Kubernetes situations?

Coming up with a couple of examples would probably be a great way to make progress.

**Comment by ChristianCiach** [comment]
We have a similar use case, so I hope it is okay to add it to this issue.

We are currently using kbld in the simpliest way possible: 

```
kustomize build ... | kbld -f-
```

There is no `ImagesLock` involved; we just want to resolve all images to their digests on every deployment.

But now we are planning to create a `CronJob` that *needs to reference a mutable image tag*. The CronJob runs some kind of auto-updater, so it is very important that the container used by the CronJob uses the *latest* image referenced by the image tag on every job execution (using `imagePullPolicy: Always`). We are now looking for a way to exclude specific containers from `kbld`-resolving and we would like to do that via annotations.

**Comment by ChristianCiach** [comment]
It just occurs to me that I can probably workaround this issue by using a `Config` manifest (`kbld.k14s.io/v1alpha1`) where I can set `preresolved: true` for that image. I will update this comment later to report if that works or not.

**Comment by joaopapereira** [comment]
If you use the `preresolved: true` for that particular image it should work. something like
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kbld-test1
spec:
  selector:
    matchLabels:
      app: kbld-test1
  template:
    metadata:
      labels:
        app: kbld-test1
    spec:
      containers:
      - name: my-app
        image: nginx:1.14.2
        #!      ^-- image reference in its tag form
---
apiVersion: kbld.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.17.0
overrides:
- image: nginx:1.14.2
  newImage: nginx:1.14.2
  preresolved: true
```
If you use the above with `kbld` you would get the output:
```
resolve | final: nginx:1.14.2 -> nginx:1.14.2
---
apiVersion: apps/v1
  1 ---
kind: Deployment
metadata:
  annotations:
    kbld.k14s.io/images: |
      - origins:
        - preresolved:
            url: nginx:1.14.2
        url: nginx:1.14.2
  name: kbld-test1
spec:
  selector:
    matchLabels:
      app: kbld-test1
  template:
    metadata:
      labels:
        app: kbld-test1
    spec:
      containers:
      - image: nginx:1.14.2
        name: my-app

Succeeded
```

**Comment by ChristianCiach** [comment]
We've used the above workaround for quite a while with good success:

```yaml
apiVersion: kbld.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.17.0
overrides:
- image: nginx:1.14.2
  newImage: nginx:1.14.2
  preresolved: true
```

But now we want to call `kbld` with `--imgpkg-lock-output` which results in an error:

```
$ kbld --imgpkg-lock-output lockfile.yaml -f kubernetes.yaml 
resolve | final: docker.io/library/nginx:1.14.2 -> docker.io/library/nginx:1.14.2
kbld: Error: Validating images lock:
  Expected ref to be in digest form, got 'docker.io/library/nginx:1.14.2'
```

It feels like we are using the `overrides[].preresolved: true` for something it never was intended for. It would be nice if `kbld` offered a better way to ignore/exclude specifig images from getting resolved.
