### ISSUE TITLE
kbld does not fully respect Block Chomping Indicator in manifest

### ISSUE THREAD

**Issue by mkurde** [carvel-dev/kbld#178]
**What steps did you take:**

kbld is the last step after rendering all my manifests in my deploy automation. Therefor, also manifests which do not have docker images are going through this process. I am working on Prometheus Alerting manifests and here is an example:

```yaml
apiVersion: 'monitoring.coreos.com/v1'
kind: 'PrometheusRule'
metadata:
  name: 'alert-kube-state-container'
  namespace: 'monitoring'
  labels:
    prometheus.monitoring: 'enabled'
    helm.sh/chart: 'alerts-1.0.0'
spec:
  groups:
    - name: 'KubeStateContainer'
      rules:
        - alert: 'Container unready'
          expr: >-
            kube_pod_container_status_ready < 1
            and on (pod, container)
            kube_pod_container_status_terminated_reason{reason="Completed"} == 0
          for: '15m'
          labels:
            severity: 'warning'
            service: 'kube-state-container'
          annotations:
            summary: 'Container(s) unready'
            description: |
              Container `{{ $labels.container }}` has been "Unready" for
              more than 15 minutes.
              Pod: `{{ $labels.pod }}`.
              Check container status and logs.
```

and the result after kbld:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    helm.sh/chart: alerts-1.0.0
    prometheus.monitoring: enabled
  name: alert-kube-state-container
  namespace: monitoring
spec:
  groups:
  - name: KubeStateContainer
    rules:
    - alert: Container unready
      annotations:
        description: |
          Container `{{ $labels.container }}` has been "Unready" for
          more than 15 minutes.
          Pod: `{{ $labels.pod }}`.
          Check container status and logs.
        runbook_url: ""
        summary: Container(s) unready
      expr: kube_pod_container_status_ready < 1 and on (pod, container) kube_pod_container_status_terminated_reason{reason="Completed"}
        == 0
      for: 15m
      labels:
        service: kube-state-container
        severity: warning
```

The result is the same when the expression is in one line like

```yaml
          expr: 'kube_pod_container_status_ready < 1 and on (pod, container) kube_pod_container_status_terminated_reason{reason="Completed"} == 0'
```

**What happened:**

Next to changes like order and indentation (which is still valid yaml) you see the `expr:` line. kbld converts the Block Chomping Indicator `>-` into `:` and formats the expression into one line except the last chars `== 5` which are wrapped into the next line. This breaks yaml.

As you can see, the description with the Block Chomping Indicator `|` is rendered perfectly fine. I can not use `|` since it keeps the line breaks. 

```
>, |: "clip": keep the line feed, remove the trailing blank lines.
>-, |-: "strip": remove the line feed, remove the trailing blank lines.
```
Source: [Stackoverflow](https://stackoverflow.com/a/21699210/1161265)

**What did you expect:**

I expect to get valid yaml out of kbld when I use any [Block Chomping Indicator](https://yaml.org/spec/1.2.2/#8112-block-chomping-indicator) like `>-`. Either the given syntax is preserved or the expression is not wrapped and `:` is returned.

I won't be bother if the result is a still valid yaml since the original version with the `>-` syntax is purely used to improve the readability. 

**Anything else you would like to add:**

n/a

**Environment:**

- kbld version (use `kbld --version`): 
	- k14s/tap/kbld: stable v0.27.0
	- 0.31.0 `brew install vmware-tanzu/carvel/kbld`
- OS (e.g. from `/etc/os-release`): macOS

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by dsiebel** [comment]
I can confirm that this seems to be a regression that was introduced between `0.30.0` and `0.31.0`. I rendered the above manifests using `0.30.0` without the mentioned issue, then upgraded to `0.31.0` and was able to reproduce it.

**Comment by dsiebel** [comment]
Looks like this might be an issue with `go-yaml` which was update from 2.3.0 to 2.4.0 in kbld 0.31.0.
[`v2.3.0...v2.4.0`#diff-18f184a5d0](https://github.com/go-yaml/yaml/compare/v2.3.0...v2.4.0#diff-18f184a5d04563c70b17eaa2a44c42850ed8461714b0632d6593cacf3147b28cL89)

EDIT:
It looks like it can be controlled with this

```
// The API does not allow this process to be reversed as it's intended
// for migration only. v3 drops this method and instead offers more
// control on a per encoding basis.
yaml.FutureLineWrap()
```

**Comment by aaronshurley** [comment]
@mkurde Thank you for reporting this bug and @dsiebel thank you for digging into this. I was able to replicate this with the provided information. We did have quite a few dependency bumps in the 0.31.0 release which likely led to this regression. I'll mark this as `important-soon`  since it's a regression. Due to KubeCon this week, it might be unlikely that we get to this until next week or so.

We'd be open to a PR if either of you would like to dig into this, just let us know if you run into any issues/questions.

**Comment by cppforlife** [comment]
> ...formats the expression into one line except the last chars == 5 which are wrapped into the next line. This breaks yaml....
> I won't be bother if the result is a still valid yaml since the original version with the >- syntax is purely used to improve the readability.

im not sure i fully groked the issue. result is a valid yaml, though line folded (as example shows below ytt for example using a yaml library reads that yaml).

is there particular yaml parser that does not understand that line folding?

example:

```
% pbpaste|kbld -f-
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    helm.sh/chart: alerts-1.0.0
    prometheus.monitoring: enabled
  name: alert-kube-state-container
  namespace: monitoring
spec:
  groups:
  - name: KubeStateContainer
    rules:
    - alert: Container unready
      annotations:
        description: |
          Container `{{ $labels.container }}` has been "Unready" for
          more than 15 minutes.
          Pod: `{{ $labels.pod }}`.
          Check container status and logs.
        summary: Container(s) unready
      expr: kube_pod_container_status_ready < 1 and on (pod, container) kube_pod_container_status_terminated_reason{reason="Completed"}
        == 0
      for: 15m
      labels:
        service: kube-state-container
        severity: warning
```

```
% pbpaste|kbld -f-|ytt -f-
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    helm.sh/chart: alerts-1.0.0
    prometheus.monitoring: enabled
  name: alert-kube-state-container
  namespace: monitoring
spec:
  groups:
  - name: KubeStateContainer
    rules:
    - alert: Container unready
      annotations:
        description: |
          Container `{{ $labels.container }}` has been "Unready" for
          more than 15 minutes.
          Pod: `{{ $labels.pod }}`.
          Check container status and logs.
        summary: Container(s) unready
      expr: kube_pod_container_status_ready < 1 and on (pod, container) kube_pod_container_status_terminated_reason{reason="Completed"} == 0
      for: 15m
      labels:
        service: kube-state-container
        severity: warning
```
