### ISSUE TITLE
Environment variable is passed with single quotes to pack and is not used

### ISSUE THREAD

**Issue by cxhrouet** [carvel-dev/kbld#221]
**What steps did you take:**
- Get a sample Java application : `git clone https://github.com/spring-projects/spring-petclinic.git && cd spring-petclinic`
- Write a `kbld.yml` file to build image from source following https://carvel.dev/kbld/docs/v0.32.0/building/ :
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kbld-test1
spec:
  selector:
    matchLabels:
      app: kbld-test1
  template:
    metadata:
      labels:
        app: kbld-test1
    spec:
      containers:
      - name: my-app
        image: spring-petclinic
---
apiVersion: kbld.k14s.io/v1alpha1
kind: Config
sources:
- image: spring-petclinic
  path: .
  pack:
    build:
      builder: paketobuildpacks/builder:full
      rawOptions: ["-v"]
      rawOptions: ["-e BP_JVM_VERSION=8"]
```
- Launch : `kbld -f kbld.yml`

**What happened:**
Environment variable is passed with single quotes to pack and the buildpack cannot interpret it and JVM 11 is selected :

```
spring-petclinic | Provided Environment Variables
spring-petclinic |   'BP_JVM_VERSION=8'
```
```
spring-petclinic | Paketo BellSoft Liberica Buildpack 9.1.0
spring-petclinic |   https://github.com/paketo-buildpacks/bellsoft-liberica
spring-petclinic |   Build Configuration:
spring-petclinic |     $BP_JVM_TYPE                 JRE             the JVM type - JDK or JRE
spring-petclinic |     $BP_JVM_VERSION              11              the Java version
```

**What did you expect:**
The same behavior as building directly with pack : 
`pack build spring-petclinic --builder paketobuildpacks/builder:full -v -e BP_JVM_VERSION=8`

which gives:

```
Provided Environment Variables
  BP_JVM_VERSION=8
```

```
Paketo BellSoft Liberica Buildpack 9.1.0
  https://github.com/paketo-buildpacks/bellsoft-liberica
  Build Configuration:
    $BP_JVM_TYPE                 JRE             the JVM type - JDK or JRE
    $BP_JVM_VERSION              8               the Java version
```

**Environment:**

- kbld version (use `kbld --version`): 0.32.0
- Docker registry used (e.g. `Docker HUB`): n/a
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04.3 LTS

If building images using `pack`
- Pack Version (e.g. `pack version`): 0.24.0+git-79a40b7.build-3148

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.
