### ISSUE TITLE
kbld should be smart enough to see a Carvel tagSelection without additional work

### ISSUE THREAD

**Issue by voor** [carvel-dev/kbld#295]
**Describe the problem/challenge you have**
I have a repository: https://gitlab.com/tanzuplatform/platform-services and it contains a bunch of manifests and other package installs that help populate a k8s cluster with all the joys of production-readiness.

Some folks have used this repository and deployed things well, since those clusters were internet accessible.  Somebody wanted to use this repository in a place that _did not_ have internet accessibility, which means they need to relocate everything.  Well, easy problem, I have `kbld`.... *except* lo and behold I'm _also_ using some Carvel-isms like `tagSelection`:

```
ytt -f stack/common/manifests --data-values-file stack/common/values/ghost | kbld -f - >/dev/null
kbld: Error: 
- Resolving image 'us-east4-docker.pkg.dev/pa-rvanvoorhees/packages/imgpkg/charts/phantom-repository': GET https://us-east4-docker.pkg.dev/v2/pa-rvanvoorhees/packages/imgpkg/charts/phantom-repository/manifests/latest: MANIFEST_UNKNOWN: Failed to fetch "latest"
- Resolving image 'us-east5-docker.pkg.dev/pa-rvanvoorhees/carvel/imgpkg/phantom-repository': GET https://us-east5-docker.pkg.dev/v2/pa-rvanvoorhees/carvel/imgpkg/phantom-repository/manifests/latest: MANIFEST_UNKNOWN: Failed to fetch "latest"
- Resolving image 'us-east5-docker.pkg.dev/pa-rvanvoorhees/carvel/imgpkg/tap-repository': GET https://us-east5-docker.pkg.dev/v2/pa-rvanvoorhees/carvel/imgpkg/tap-repository/manifests/latest: MANIFEST_UNKNOWN: Failed to fetch "latest"
- Resolving image 'us-east5-docker.pkg.dev/pa-rvanvoorhees/carvel/imgpkg/tanzu-data-services-repository': GET https://us-east5-docker.pkg.dev/v2/pa-rvanvoorhees/carvel/imgpkg/tanzu-data-services-repository/manifests/latest: MANIFEST_UNKNOWN: Failed to fetch "latest"
- Resolving image 'us-east5-docker.pkg.dev/pa-rvanvoorhees/carvel/imgpkg/rabbitmq-repository': GET https://us-east5-docker.pkg.dev/v2/pa-rvanvoorhees/carvel/imgpkg/rabbitmq-repository/manifests/latest: MANIFEST_UNKNOWN: Failed to fetch "latest"
- Resolving image 'us-east5-docker.pkg.dev/pa-rvanvoorhees/carvel/imgpkg/tkg-standard-repository': GET https://us-east5-docker.pkg.dev/v2/pa-rvanvoorhees/carvel/imgpkg/tkg-standard-repository/manifests/latest: MANIFEST_UNKNOWN: Failed to fetch "latest"
```

:oh-no: 

**Describe the solution you'd like**
I can already fix this today, I just need to do something like this:

```
#@ load("@ytt:data", "data")

---
apiVersion: kbld.k14s.io/v1alpha1
kind: ImageOverrides
overrides:
- image: #@ "{}/tap-repository".format(data.values.oci_registry)
  newImage: #@ "{}/tap-repository".format(data.values.oci_registry)
  tagSelection:
    semver:
      constraints: ">1.1.0"
      prereleases:
        identifiers: [build]
- image: #@ "{}/tkg-standard-repository".format(data.values.oci_registry)
  newImage: #@ "{}/tkg-standard-repository".format(data.values.oci_registry)
  tagSelection:
    semver:
      constraints: ">0.0.0"
      prereleases: {}
- image: #@ "{}/rabbitmq-repository".format(data.values.oci_registry)
  newImage: #@ "{}/rabbitmq-repository".format(data.values.oci_registry)
  tagSelection:
    semver:
      constraints: ">0.0.0"
      prereleases: {}
- image: #@ "{}/tanzu-data-services-repository".format(data.values.oci_registry)
  newImage: #@ "{}/tanzu-data-services-repository".format(data.values.oci_registry)
  tagSelection:
    semver:
      constraints: ">0.0.0"
      prereleases: {}
- image: #@ "{}/phantom-repository".format(data.values.oci_registry)
  newImage: #@ "{}/phantom-repository".format(data.values.oci_registry)
  tagSelection:
    semver:
      constraints: ">0.0.0"
      prereleases: {}

```

But let's be honest, do you think the average user is going to be smart enough to know to do that?  I don't know, probably not.

What if kbld could just see that `tagSelection` is in play, and instead of using the `image:` field along, incorporate that vendir lookup in the process?

**Anything else you would like to add:**
I was able to solve this problem today because I found https://github.com/vmware-tanzu/carvel-kbld/issues/51

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.
