### ISSUE TITLE
keymatcher ignores path if name is set

### ISSUE THREAD

**Issue by cjnosal** [carvel-dev/kbld#326]
**What steps did you take:**
The [key-matcher docs](https://carvel.dev/kbld/docs/v0.36.0/config/#key-matcher) lists `name` and `path` as children of `keyMatcher` and describes each. I tried to write the following matcher using both fields:
```
keyMatcher:
- name: value
  path: [spec, template, spec, containers, {index: 0}, env, {index: 0}]
```

**What happened:**
Kbld treated all `value` fields at any path as images

**What did you expect:**
Only the `value` child at the specific `env` index would be treated as an image.

**Anything else you would like to add:**
The [code](https://github.com/carvel-dev/kbld/blob/develop/pkg/kbld/search/rule_matcher.go#L29) currently treats `name` and `path` as mutually exclusive. If this is intentional it should be called out in the docs.

**Environment:**

- kbld version (use `kbld --version`): 0.36.1

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by Zerpet** [comment]
> The [code](https://github.com/carvel-dev/kbld/blob/develop/pkg/kbld/search/rule_matcher.go#L29) currently treats name and path as mutually exclusive. If this is intentional it should be called out in the docs.

Thank you, this resolved the problem for me. I stumbled upon this issue, having the same problem. As an example, the following YAML:

<details><summary>spec.yml</summary>

```yaml
spec:
  template:
    spec:
      containers:
        - name: example
          env:
            - name: please-ignore-me
              something-else: yes
            - name: ignore-me-too
              not-a-value: definitely not
            - name: resolve-me
              value: busybox:latest
            - name: not-me
              value: not-an-image
```

</details>

With the following kbld configuration:

<details><summary>kbld-conf.yml</summary>

```yaml
---
apiVersion: kbld.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.30.0
searchRules:
  - keyMatcher:
      name: value
      path: [spec, template, spec, containers, {index: 0}, env, {index: 2}, value]
```

</details>

Results in an error, because `kbld` search rules [1] implicitly take precedence on `name`. This behaviour is not documented [in the relevant doc](https://carvel.dev/kbld/docs/v0.45.x/config/#key-matcher) section, and it can lead to confusion.

To resolve my particular use case (search rule to resolve exactly one element in the array), I had to remove `name` from kbld config like so:

<details><summary>kbld-conf.yml</summary>

```yaml
---
apiVersion: kbld.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.30.0
searchRules:
  - keyMatcher:
      path: [spec, template, spec, containers, {index: 0}, env, {index: 2}, value]
```

</details>

[1] relevant code
https://github.com/carvel-dev/kbld/blob/f3e483f2758a664ae3db9b120b286f264cf55036/pkg/kbld/search/rule_matcher.go#L27-L31
