### ISSUE TITLE
[builder] add ko as a backend

### ISSUE THREAD

**Issue by aaronshurley** [carvel-dev/kbld#37]
Some users want to use [`ko`](https://github.com/google/ko) as a backend (i.e. an image-building option).

Proposed Workflow:
- We want to preserve as much existing `kbld` behavior as possible, so we'll only use `ko` for building images and not for publishing images.
- To use `ko` for building, we can simply use `ko publish --local`. This will build images to the local Docker. `kbld` can then reference the local image for publishing.
- We expect this to integrate fairly easily in the existing code (similar to `pack`).

Example CR:
```
---
apiVersion: kbld.k14s.io/v1alpha1
kind: Sources
sources:
- image: image1
  path: src/
  ko:
    build:
      rawOptions: ["--disable-optimizations"]
```

`ko.build.rawOptions ([]string)`: Refer to `ko publish -h` for all available flags

We didn't know what the rules/patterns were for docker and pack build options so we just opted for the simplest form.
