### ISSUE TITLE
docker buildx have different output depending on the driver used

### ISSUE THREAD

**Issue by joaopapereira** [carvel-dev/kbld#451]
**What steps did you take:**
when running kbld with a docker buildx configuration if the builder is not kubernetes it fails to push the images.

**What happened:**
```yaml #config.yml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kbld-test1
spec:
  selector:
    matchLabels:
      app: kbld-test1
  template:
    metadata:
      labels:
        app: kbld-test1
    spec:
      containers:
      - name: my-app
        image: simple-app
---
apiVersion: kbld.k14s.io/v1alpha1
kind: Config
sources:
- image: simple-app
  path: dev-util
  docker:
    buildx:
      rawoptions:
      - --platform
      - linux/amd64
destinations:
- image: simple-app
  newImage: docker.io/rkamaldocker/simple-app
```

Error:

```
kbld: Error:
- Resolving image 'simple-app': Expected to find image digest in build output but did not
```

**What did you expect:**
No error

**Anything else you would like to add:**
This is what kbld is looking for in the output of buildx: `pushing manifest for .*@sha256:([0-9a-z]+)`
but in this case you have
`pushing [docker.io/rkamaldocker/simple-app:rand-169723384850284148-1834444161104-simple-app](http://docker.io/rkamaldocker/simple-app:rand-169723384850284148-1834444161104-simple-app) with docker`

**Environment:**

- kbld version (use `kbld --version`): All
- Docker registry used (e.g. `Docker HUB`): NA
- OS (e.g. from `/etc/os-release`): All

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.
