### ISSUE TITLE
support image override to pick latest version based on semver constrain

### ISSUE THREAD

**Issue by StarpTech** [carvel-dev/kbld#51]
Extend `kbld` to support a semver lock on arbitrary images. Basically, when an image is being resolved it would be constrained to some range `nginx:1.3.x` of tags and the latest within that tag range is picked.

## Why

This is very useful if you have to deal with dynamic environments. Instead to maintain and communicate none-breaking changes we could automate it.

## How 

```yaml
apiVersion: kbld.k14s.io/v1alpha1
kind: ImageOverrides
overrides:
- image: team-B-order-service
  semverLock: 1.14.x
```

Related: https://docs.fluxcd.io/en/latest/tutorials/driving-flux/

**Comment by cppforlife** [comment]
could reuse functionality from vendir's https://github.com/k14s/vendir/issues/10

**Comment by StarpTech** [comment]
How can I help? I saw that you land semver-constraints in vendir https://github.com/k14s/vendir/releases/tag/v0.11.0.

**Comment by StevenLocke** [comment]
Thanks for raising your hand! There's always more for us to do and we appreciate the help.  If you want to pick this up and move it forward:

* Take inspiration from the vendir work, use the same library for consistency
* The general flow for resolving an image would be something like: fetch all tags, narrowing them to the ones that are in semver format, selecting the one which is latest and fulfills the given constraint
* This is probably happening inside `pkg/kbld/image/`

**Comment by cppforlife** [comment]
> Take inspiration from the vendir work, use the same library for consistency

just fyi, since vendir work just landed recently, we may change how we use that library as we receive feedback from folks that requested that feature.

**Comment by cppforlife** [comment]
following convetion from vendir this is probably what we would want as an API for this:

```yaml
apiVersion: kbld.k14s.io/v1alpha1
kind: ImageOverrides
overrides:
- image: team-B-order-service
  newImage: docker.io/foo/team-b-order-service
  tagSelection:
    semver:
      constraints: "~>1.14"
```
