### ISSUE TITLE
kbld docker source - pre-build docker image

### ISSUE THREAD

**Issue by BenChand** [carvel-dev/kbld#536]
**Describe the problem/challenge you have**
[A description of the current challenge that you are experiencing.]

I'm building the docker image to be bundled using nix, not with a Dockerfile. At the moment I have to do something like this to use my nix-docker-image as a base image for the kbld-docker-image:

```
sources:
- image: my-image
  path: .
  docker:
    build:
      pull: false
      noCache: true
```

Dockerfile:
```
FROM nix-docker-image:latest
CMD ["my-app"]
```

**Describe the solution you'd like**
[A clear and concise description of what you want to happen. If applicable a visual representation of the UX (ex: new CLI argument name, the behavior expected).]

Allow me to point to an image already built in my local docker images:

```
sources:
- image: my-image
  path: .
  docker:
    name: nix-docker-image
    tag: latest
```

**Anything else you would like to add:**
[Additional information that will assist in solving the issue.]

Alternatively, support nix (flakes 🤞🏼) in general and allow me to point to a nix package that resolves to a docker image:

```
sources:
- image: my-image
   nix:
     flake:
       file: ./flake.nix
       package: 'docker' # nix build .#docker
```

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.
