### ISSUE TITLE
Error parsing reference: ":" is not a valid repository/tag: invalid reference format

### ISSUE THREAD

**Issue by HamishWHC** [carvel-dev/kbld#548]
**What steps did you take:**
I am running kbld on a simple (single deployment with two containers) manifest with a configuration that has a source and a destination defined. I want to use `ghcr.io/HamishWHC/simple-example-image` as the `newImage` for the destination.

**What happened:**
After the image builds successfully, I get the following error:
```
ghcr.io/HamishWHC/simple-image-example | starting push (using Docker): kbld:simple-image-example-sha256-3ae337ef4c382b9e16dc373ac151ff73da0795e6c5accd1951d0eb75a62793b7 -> :
ghcr.io/HamishWHC/simple-image-example | Error parsing reference: ":" is not a valid repository/tag: invalid reference format
ghcr.io/HamishWHC/simple-image-example | tag error: exit status 1
ghcr.io/HamishWHC/simple-image-example | finished push (using Docker)
kbld: Error: 
- Resolving image 'simple-image-example': exit status 1
```

**What did you expect:**
I expected kbld to successfully push the image.

**Anything else you would like to add:**
Manifest and config:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-example-deployment-c81d9144
spec:
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  replicas: 2
  selector:
    matchLabels:
      cdk8s.io/metadata.addr: simple-example-deployment-c8904b4a
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        cdk8s.io/metadata.addr: simple-example-deployment-c8904b4a
    spec:
      automountServiceAccountToken: false
      containers:
        - image: simple-image-example
          imagePullPolicy: Always
          name: main
          resources:
            limits:
              cpu: 1500m
              memory: 2048Mi
            requests:
              cpu: 1000m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
        - image: nginx:latest
          imagePullPolicy: Always
          name: main
          resources:
            limits:
              cpu: 1500m
              memory: 2048Mi
            requests:
              cpu: 1000m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
      dnsPolicy: ClusterFirst
      hostNetwork: false
      restartPolicy: Always
      securityContext:
        fsGroupChangePolicy: Always
        runAsNonRoot: true
      setHostnameAsFQDN: false
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30
---
apiVersion: kbld.k14s.io/v1alpha1
kind: Config
metadata:
  name: simple-example-kbld-config-c892ee7d
destinations:
  - image: simple-image-example
    newImage: ghcr.io/HamishWHC/simple-image-example
sources:
  - image: simple-image-example
    path: examples
```

**Environment:**

- kbld version (use `kbld --version`): 0.46.0
- Docker registry used (e.g. `Docker HUB`): GHCR
- OS (e.g. from `/etc/os-release`): macOS 15.5
- Docker CLI Version (e.g. `docker version`): 28.1.1

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.
