### ISSUE TITLE
Can kbld have workaround with manifests (Harbor)

### ISSUE THREAD

**Issue by mhoshi-vm** [carvel-dev/kbld#70]
Due to recent DockerHub 429 issues, i really like kbld to be a solution to reallocating images to private registries.
However due to Harbor not supporting manifests, I am unable to reallocate the simplest alpine image.

```
% cat manifest.lock
apiVersion: kbld.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.25.0
overrides:
- image: alpine
  newImage: index.docker.io/library/alpine@sha256:c0e9560cda118f9ec63ddefb4a173a2b2a0347082d7dff7dc14272e7841a5b5a
  preresolved: true
```

```
% kbld relocate -f ./manifest.lock --repository 10.195.35.69/machi/concourse --lock-output ./manifest.lock.copied
relocate | exporting 1 images...
relocate | will export index.docker.io/library/alpine@sha256:c0e9560cda118f9ec63ddefb4a173a2b2a0347082d7dff7dc14272e7841a5b5a
relocate | exported 1 images
relocate | importing 1 images...
relocate | importing index.docker.io/library/alpine@sha256:c0e9560cda118f9ec63ddefb4a173a2b2a0347082d7dff7dc14272e7841a5b5a -> 10.195.35.69/machi/concourse@sha256:c0e9560cda118f9ec63ddefb4a173a2b2a0347082d7dff7dc14272e7841a5b5a...
relocate | imported 0 images
kbld: Error: Importing image index.docker.io/library/alpine@sha256:c0e9560cda118f9ec63ddefb4a173a2b2a0347082d7dff7dc14272e7841a5b5a:
  Importing image index as 10.195.35.69/machi/concourse@sha256:c0e9560cda118f9ec63ddefb4a173a2b2a0347082d7dff7dc14272e7841a5b5a:
    Writing image index:
      Retried 5 times:
        PUT https://10.195.35.69/v2/machi/concourse/manifests/kbld-sha256-c0e9560cda118f9ec63ddefb4a173a2b2a0347082d7dff7dc14272e7841a5b5a:
          UNSUPPORTED_MEDIA_TYPE:
            Manifest.list is not supported.; Manifest.list is not supported.
```

Can we have some solution to overcome this manifests issue ?
