### ISSUE TITLE
support hostname + base path rewrite

### ISSUE THREAD

**Issue by cppforlife** [carvel-dev/kbld#80]
**Describe the problem/challenge you have**

jfrog supports a way to proxy image downloads from a particular hostname + base path (e.g. jfrog.corp.com/project-x proxies all requests to upstream-registry.com/some-path). it should be possible to rewrite lock file to rewrite lock entries.

**Describe the solution you'd like**

if user is using imgpkg bundles then i think there would be no need for this since bundle would be proxied and found in the virtual repo. .imgpkg/images.yml should be relative to that location.

should we have a feature in kbld that facilities rewriting hostnames, not sure...

**Anything else you would like to add:**

https://www.jfrog.com/confluence/display/JFROG/Docker+Registry#DockerRegistry-VirtualDockerRepositories ?

**Comment by pivotaljohn** [comment]
**As** someone installing an app containing a bunch of images
**And** I have a virtual repository configured (which includes all of the possible source registries that I'd pull my images from)
**I want to** be able to rewrite my `ImagesLock` such so I'd obtain all of those images from that virtual repository


For example:

Given an initial `ImagesLock`:
```yaml
# images.yml
apiVersion: imgpkg.carvel.dev/v1alpha1
kind: ImagesLock
images:
- image: index.docker.io/dkalinin/k8s-simple-app@sha256:4c8b96d4fffdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
  annotations:
    kbld.carvel.dev/id: docker.io/dkalinin/k8s-simple-app
- image: gcr.io/k8slt/k8s-simple-app2@sha256:deadbeef4c8b96d4fffdfae29258d94a22ae4ad1fe36139d47288b8960d9958d
  annotations:
    kbld.carvel.dev/id: gcr.io/k8slt/k8s-simple-app2
```

JFrog Artifactory is configured with with this Virtual Repository:
- Repository Key: `jfrog.corp.com/k8slt`
   Selected repositories:
   - `index.docker.io/dkalinin/k8s-simple-app`
   - `gcr.io/k8slt/k8s-simple-app2`

```console
$ kbld rewrite -f images.yml --to-repo jfrog.corp.com/k8slt
apiVersion: imgpkg.carvel.dev/v1alpha1
kind: ImagesLock
images:
- image: jfrog.corp.com/k8slt@sha256:4c8b96d4fffdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
  annotations:
    kbld.carvel.dev/id: docker.io/dkalinin/k8s-simple-app
- image: jfrog.corp.com/k8slt@sha256:deadbeef4c8b96d4fffdfae29258d94a22ae4ad1fe36139d47288b8960d9958d0
  annotations:
    kbld.carvel.dev/id: gcr.io/k8slt/k8s-simple-app2
```

## `imgpkg` already handles this... for bundles

Since `imgpkg pull` will detect whether or not all of the images were pulled from the same repository, given the Artifactory configuration, above, it _will_ rewrite the `ImagesLock` as described above. Assuming the user is using bundles.

It does the thing that's requested.

## Should `kbld`?
So, the question is:

Is it in `kbld`'s scope to support this scenario, independently (i.e. not relying on `imgpkg copy/pull` for the relocation)?
