### ISSUE TITLE
imgpkg ImagesLock file changed format

### ISSUE THREAD

**Issue by joaopapereira** [carvel-dev/kbld#86]
**Describe the problem/challenge you have**
Allows us to have better package boundaries and import a small ImagesLock package into `kbld` instead of duplicating the ImagesLock logic. This will help keep `kbld` and `imgpkg` in sync wrt `imgpkg` lock files.

**Describe the solution you'd like**
**Given** I am in the kbld github repository
**And** want to generate OCI images using the following configuration
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kbld-simple-app
spec:
  selector:
    matchLabels:
      app: kbld-simple-app
  template:
    metadata:
      labels:
        app: kbld-simple-app
    spec:
      containers:
      - name: my-app
        image: simple-app
---
apiVersion: kbld.k14s.io/v1alpha1
kind: Config
sources:
- image: simple-app
  path: test/e2e/assets/simple-app
destinations:
- image: simple-app
  newImage: localhost:5000/kbld-simple-app2
```
**When** I execute `kbld --imgpkg-lock-output /tmp/simple-app-package/.imgpkg/images.yml -f build.yml`
**Then** I should see the following content on the file `/tmp/simple-app-package/.imgpkg/images.yml`
```
apiVersion: imgpkg.carvel.dev/v1alpha1
kind: ImagesLock
images:
- annotations:
    kbld.carvel.dev/id: simple-app
  image: localhost:5000/kbld-simple-app2@sha256:ed98e4fb24d5ef564cbbccfacf7fb4fa57ddaa09c16f14c336d08c79f930672a
```
---

**Given** I have ImagesLock file generated from kbld 
**When** I execute `imgpkg push -f /tmp/simple-app-package/ -b localhost:5000/test-simple-image`
**Then** I should see 
```
dir: .
dir: .imgpkg
file: .imgpkg/images.yml
Pushed 'localhost:5000/test-simple-image@sha256:e49a95f408aabf408c475f3f0aef699a104e5355bb75da062ef376a14578acfc'
Succeeded
```
---

** Given** a developer/operator 
** When ** I try to include imgpkg's imageLock file package in kbld and use it
** Then ** I should know how exactly I can use and apply imgpkg's  imageLock file package
